#!/bin/bash

SSLDIR=${HOME}/ssl
TEMP_X86_64=${HOME}/ssl-x86_64
TEMP_ARM64=${HOME}/ssl-arm64
DEBUG=""
MEMDEBUG_OPTIONS=""
OPENSSL_OPTIONS="no-ssl2 no-ssl3 no-hw no-engine no-psk no-srp no-weak-ssl-ciphers"

while [[ $# -gt 0 ]]; do
  case $1 in
    -d|-debug|--debug|debug)
      DEBUG="--debug"
      SSLDIR=${HOME}/ssl-debug
      MEMDEBUG_OPTIONS="enable-crypto-mdebug enable-crypto-mdebug-backtrace"
      echo "Building debug mode"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      shift # past argument
      ;;
  esac
done

make clean
rm -rf ${SSLDIR}
rm -rf ${TEMP_X86_64}
rm -rf ${TEMP_ARM64}

./Configure ${OPENSSL_OPTIONS} ${MEMDEBUG_OPTIONS} darwin64-x86_64-cc -mmacosx-version-min=10.12 --prefix=${SSLDIR} --openssldir=${SSLDIR} ${DEBUG}
make depend
make
make install_sw

mv ${SSLDIR}/ ${TEMP_X86_64}

make clean
./Configure ${OPENSSL_OPTIONS} ${MEMDEBUG_OPTIONS} darwin64-arm64-cc -mmacosx-version-min=10.12 --prefix=${SSLDIR} --openssldir=${SSLDIR} ${DEBUG}
make depend
make
make install_sw

mv ${SSLDIR}/ ${TEMP_ARM64}

make install_ssldirs

mkdir -p ${SSLDIR}/bin
mkdir -p ${SSLDIR}/include/openssl
mkdir -p ${SSLDIR}/lib

cp ${TEMP_ARM64}/include/openssl/* ${SSLDIR}/include/openssl

if [ -n $DEBUG ]
then
    mkdir -p ${SSLDIR}/include/internal
    mkdir -p ${SSLDIR}/include/crypto
    mkdir -p ${SSLDIR}/apps
    cp ./include/internal/*.h ${SSLDIR}/include/internal
    cp ./include/crypto/*.h ${SSLDIR}/include/crypto
    cp ./*.h ${SSLDIR}/apps
    cp ./apps/*.h ${SSLDIR}/apps
    cp ./apps/*.c ${SSLDIR}/apps
fi

lipo -create ${TEMP_X86_64}/lib/libcrypto.a \
             ${TEMP_ARM64}/lib/libcrypto.a \
             -output ${SSLDIR}/lib/libcrypto.a

lipo -create ${TEMP_X86_64}/lib/libssl.a \
             ${TEMP_ARM64}/lib/libssl.a \
             -output ${SSLDIR}/lib/libssl.a

lipo -create ${TEMP_X86_64}/bin/openssl \
             ${TEMP_ARM64}/bin/openssl \
             -output ${SSLDIR}/bin/openssl

lipo -create ${TEMP_X86_64}/lib/libcrypto.1.1.dylib \
             ${TEMP_ARM64}/lib/libcrypto.1.1.dylib \
             -output ${SSLDIR}/lib/libcrypto.1.1.dylib

lipo -create ${TEMP_X86_64}/lib/libssl.1.1.dylib \
             ${TEMP_ARM64}/lib/libssl.1.1.dylib \
             -output ${SSLDIR}/lib/libssl.1.1.dylib

ln -s ${SSLDIR}/lib/libcrypto.1.1.dylib ${SSLDIR}/lib/libcrypto.dylib
ln -s ${SSLDIR}/lib/libssl.1.1.dylib ${SSLDIR}/lib/libssl.dylib

rm -rf ${TEMP_X86_64}
rm -rf ${TEMP_ARM64}
make clean

say "Build complete"

